import type { Item, Turn } from "~/protocol";

/**
 * The portable, reader-facing version of a conversation. A transcript is the
 * exchange itself, not the machinery around it: tool calls, private thoughts,
 * notices, and prompts generated by recovery are deliberately left out.
 */
export function transcriptMarkdown(items: Item[], turns: Turn[]): string {
  const recoveredTurns = new Set(turns.filter((turn) => turn.recovery).map((turn) => turn.id));

  return items
    .filter(
      (item) =>
        item.kind === "message" &&
        item.parentId === undefined &&
        (item.role === "user" || item.role === "agent") &&
        item.contentKind !== "thought" &&
        (item.text ?? "").trim() !== "" &&
        !(
          item.role === "user" &&
          item.turnId !== undefined &&
          recoveredTurns.has(item.turnId)
        ),
    )
    .map((item) => `## ${item.role === "user" ? "User" : "Assistant"}\n\n${item.text}`)
    .join("\n\n");
}
